name: Output information
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Output information
        run: echo "${{ toJson(github) }}"